name: "workflow backend"

on:
  push:
      branches:
        - main

jobs:
  code_analysis_job:
    runs-on: ubuntu-latest

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v4

    - name: "install dependencies"
      run: npm install
    - name: "run code analysis"
      run: npm run lint
    
  unit_testing_job:

    runs-on: ubuntu-latest
    steps:
    - name: "checkout repository"
      uses: actions/checkout@v4

    - name: "install dependencies"
      run: npm install
    - name: "run code analysis"
      run: npm run test
    
  build_and_push:

    runs-on: ubuntu-latest
    needs: ["code_analysis_job", "unit_testing_job"]
    steps:
    - name: "checkout repository"
      uses: actions/checkout@v4

    - name: "build docker image"
      run: docker build -t houriamami/back-session6 .
    - name: "list docker images"
      run: docker images

    
 
 
   
   
   
   
   
   
   
   
   


  #build and push
  #deployment 