name: "workflow backend"

on:
  push:
      branches:
        - main

jobs:
  code_analysis_job:
    runs-on: ubuntu-latest

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v4

    - name: "install dependencies"
      run: npm install
    - name: "run code analysis"
      run: npm run lint
    
  unit_testing_job:

    runs-on: ubuntu-latest
    steps:
    - name: "checkout repository"
      uses: actions/checkout@v4

    - name: "install dependencies"
      run: npm install
    - name: "run unit test and generate reports"
      run: |
           mkdir -p test-reports
           # Run tests and generate the report
           npm test -- --json --outputFile=test-reports/test-report.json || true
           # Check if the report contains failures
           if grep -q '"failed": [1-9]' test-reports/test-report.json; then
             echo "Tests failed, but report will still be generated."
             echo "::error::Tests failed. Stopping workflow."
             exit 1
           fi
      shell: bash
    - name: "upload test-report as artifact"
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test-reports/test-report.json
    
    
  build_and_push:

    runs-on: ubuntu-latest
    needs: ["code_analysis_job", "unit_testing_job"]
    if: needs.unit_testing_job.result == 'success'

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v4

    - name: "build docker image"
      run: docker build -t houriamami/back-session6 .
    - name: "list docker images"
      run: docker images


    - name: "login to Docker Hub"
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: "push docker image to docker hub"
      run: docker push houriamami/back-session6

    - name: "tag image "
      run: docker tag houriamami/back-session6 houriamami/back-session6:${{github.run_number}}

    - name: "push tagged image "
      run: docker push houriamami/back-session6:${{github.run_number}}

  deployment_job:

    runs-on: ubuntu-latest
    needs: ["build_and_push"]
    steps:
    - name: "ssh access to vps and deploy"
      uses: appleboy/ssh-action@v1.2.0
      with:
          host: ${{ secrets.HOST }}
          username: user
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/user/devops-ecommerce/back
            sudo git pull
            sudo docker compose pull
            sudo docker compose up -d --force-recreate --remove-orphans
