name: "workflow backend"

on:
  push:
      branches:
        - main

jobs:
  code_analysis_jobs:
    runs-on: ubuntu-latest

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v4

    - name: "install dependencies"
      run: npm install
    - name: "run code analysis"
      run: npm run lint

    
 
 
   
   
   
   
   
   
   
   
   
   
    # -cloner le prj
   
   
    #code analysis code
    # -install des deps

    # -run code analysis

  #unit testing

  #build and push
  #deployment 